# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting sudo encode64)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias ls='lsd'
alias cat='/usr/bin/batcat'
alias vi='nvim'
alias vim='nvim'
alias catn='/usr/bin/cat'
#alias upgrade-all='pdsh -w pveseg1,pveseg2,pveseg3,redteam "apt update && apt upgrade -y && apt autoclean && apt autoremove -y"'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Función para actualizar servidores en paralelo con detección de privilegios
upgrade-all() {
    # 1. Configuración de rutas (Expandimos HOME explícitamente para evitar fallos con mkdir)
    local BASE_DIR="$HOME/logs_upgrade-all"
    local SUB_DIR="$(date +%Y-%m-%d_%H-%M-%S)"
    local FULL_PATH="$BASE_DIR/$SUB_DIR"
    local HOSTS="pveseg1 pveseg2 pveseg3 redteam iasrv"

    # 2. Comando remoto mejorado
    # Agregamos export DEBIAN_FRONTEND para que no se quede pegado esperando inputs
    local REMOTE_CMD='u_id=$(id -u); [ $u_id -eq 0 ] && s="" || s="sudo"; 
        export DEBIAN_FRONTEND=noninteractive;
        $s apt-get update && $s apt-get upgrade -y && $s apt-get autoclean && $s apt-get autoremove -y'

    # 3. Crear directorios
    mkdir -p "$FULL_PATH"

    print -P "\n🚀 Lanzando actualización remota en: %F{cyan}$HOSTS%f"
    print -P "📂 Directorio de logs: %F{yellow}$FULL_PATH/%f"
    print -P "📺 %F{grey}Mostrando salida en tiempo real...%f\n"

    # 4. Ejecución con pssh
    # -i: Muestra la salida estándar y error de cada host en la consola mientras ocurre
    # -t 0: Sin límite de tiempo
    parallel-ssh -H "$HOSTS" -i -t 0 -o "$FULL_PATH" -e "$FULL_PATH" "$REMOTE_CMD"

    # 5. Resumen de resultados (al final de toda la verbosidad)
    print "\n======================================"
    print "         RESUMEN DE RESULTADOS"
    print "======================================"

    for host in ${(z)HOSTS}; do
        # Verificamos si el archivo de log existe y tiene contenido
        if [ -s "$FULL_PATH/$host" ]; then
            # Opcional: Podrías buscar errores fatales específicos en el log aquí
            print -P "✅ %F{green}$host%f: Ejecución terminada. Log: $FULL_PATH/$host"
        else
            print -P "❌ %F{red}$host%f: ERROR (Sin respuesta o log vacío)"
        fi
    done
    print -P "======================================\n"
}

##Alias para identificar whois de un domino
#alias domaindata='read "d?Dominio a auditar: "; t=".${d##*.}"; s=$(whois -h whois.iana.org "$t" | grep "whois:" | awk '{print $2}'); [ -n "$s" ] && whois -h "$s" "$d" | grep -iE "Domain Name:|Creation Date:|Registry Expiry Date:|Registrar URL:|Name Server:" | sort -u || echo "Error: No se encontró servidor para $t"'
domaindata() {
    local d t s
    read "d?Dominio a auditar: "
    t=".${d##*.}"
    s=$(whois -h whois.iana.org "$t" | grep "whois:" | awk '{print $2}')
    
    if [ -n "$s" ]; then
        whois -h "$s" "$d" | grep -iE "Domain Name:|Creation Date:|Registry Expiry Date:|Registrar URL:|Name Server:" | sort -u
    else
        echo "Error: No se encontró servidor para $t"
    fi
}
